migrate_schedule.settings:
  type: config_object
  label: 'Migration schedule settings'
  mapping:
    schedules:
      type: sequence
      label: 'Per-migration schedules'
      sequence:
        type: mapping
        label: 'Migration schedule'
        mapping:
          interval:
            type: string
            label: 'Schedule interval (disabled, hourly, daily, weekly)'
          skip_if_no_changes:
            type: boolean
            label: 'Skip import if no source changes detected'
